package chatapp_server;

import java.io.*;
import java.net.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Base64;
import javax.swing.*;

public class Server extends JFrame{
    private JTextField userText;
    private JTextArea chatWindow;
    private ObjectOutputStream output;
    private ObjectInputStream input;
    private ServerSocket server;
    private Socket connection;

    // ADDED CODE
    /*
    private static AES aescipher;
    private static Vigenere vigenerecipher;
    */

    //Constructor, creating GUI here
    public Server(){
        super("Secure Instant Messenger - Server");
        userText = new JTextField();
        userText.setEditable(false);
        userText.addActionListener(
            new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    sendServerMessage(e.getActionCommand());
                    userText.setText("");
                }
            }
        );
        add(userText, BorderLayout.NORTH);
        chatWindow = new JTextArea();
        add(new JScrollPane(chatWindow));
        setSize(1000,500);
        setVisible(true);

        // ADDED CODE
        /*
        aescipher = new AES();
        aescipher.initialize_key(128);

        vigenerecipher = new Vigenere();
        vigenerecipher.generate_key();
        */
    }

    //set up and run the server
    public void startUpServer(){
        try{
            server = new ServerSocket(6789,100);
            while(true){
                //connect and maintain connection
                try{
                    waitForConnection();
                    setupStreams();
                    // ADDED CODE
                    /*
                    sendServerVigenereKey();
                    sendServerAESKey();
                    */
                    whileChatting();
                }catch(EOFException eofException){
                    showMessage("\n Server ended connection!");
                }finally {
                    closeApp();
                }
            }
        }catch(IOException ioException){
            ioException.printStackTrace();
        }
    }

    //waits for clients to connect to servers
    private void waitForConnection()throws IOException {
        showMessage("Waiting for client to connect...\n");
        connection = server.accept();
        showMessage("Now connected to "+connection.getInetAddress().getHostName());
    }

    //setup input and output streams
    private void setupStreams() throws IOException {
        output = new ObjectOutputStream(connection.getOutputStream());
        output.flush();
        input = new ObjectInputStream(connection.getInputStream());
        showMessage("\n Input and Output Streams are configured! \n");
    }

    // ADDED CODE
    /*
    // Send the AES key generated by the server
    private void sendServerAESKey(){
        try{
            output.writeObject(Base64.getEncoder().encodeToString(aescipher.getAESKey().getEncoded()));
        }catch (IOException ioexception){
            chatWindow.append("\n\nSERVER ERROR: KEY SHARING FAILED");
            ioexception.printStackTrace();
        }
    }

    // Send the Vigenere key generated by the server
    private void sendServerVigenereKey(){
        try{
            output.writeObject(vigenerecipher.getKey());
        }catch (IOException ioe){
            chatWindow.append("\n\nSERVER ERROR: Vigenere Key sending failed.");
        }
    }
    */

    //Server and Clients are connected
    //we will now be a conversation
    private void whileChatting() throws IOException{
        String message = "You are connected!\nYou can start chatting";
        //sendServerMessage(message);
        sendConnectionCompleteMessage(message);
        //allowing users to type since they are up and running
        ableToType(true);
        //have a conversation
        //where we are getting actual message
        do try {
            //message type is the actual message that comes in
            //?????Decryption occurs here??????
            message = (String) input.readObject();
            showMessage("\nCLIENT - " + message);

            // ADDED CODE
            /*
            String vd_msg;      // Vigenere Decrypted Message
            String ad_msg;      // AES Decrypted Message
            String rd_msg;      // RSA Decrypted Message

            if(message.contains("VIGENERE - "))     // If the message was encrypted with the Vigenere Cipher
            {
                vd_msg = vigenerecipher.Decrypt(vigenerecipher.getKey(), message.substring(11));
                showMessage("\nCLIENT - VIGENRE DECRYPTED: " + vd_msg); // Show the decrypted message
            }
            else if (message.contains("AES - "))    // If the message was encrypted with AES
            {
                byte[] decoded = Base64.getDecoder().decode(message.substring(6));
                ad_msg = aescipher.Decrypt(decoded, aescipher.getAESKey());
                showMessage("\nCLIENT - AES DECRYPTED: " + ad_msg);
            }
            // ELSE IF RSA GOES HERE
            */
        } catch (ClassNotFoundException classNotFound) {
            showMessage("\nCould not understand message!");
        } while(!message.equals("STOP"));
    }

    //Clean up after messaging app has been closed
    //Close streams and sockets
    private void closeApp(){
        showMessage("\nClosing Connections...\n");
        //stops users from being able to type when app is closing
        ableToType(false);
        try {
            output.close();
            input.close();
            connection.close();
        }catch(IOException ioexception){
            ioexception.printStackTrace();
        }
    }

    //Sends message to client
    private void sendServerMessage(String message) {
        try{
            // Encryption of message occurs here
            // ADDED CODE
            /*
            //VIGENERE ENCRYPTION
            String ve_message = vigenerecipher.Encrypt(vigenerecipher.getKey(), message);
            output.writeObject("VIGENERE - " + ve_message);
            output.flush();

            //AES ENCRYPTION
            byte[] ae_msg = aescipher.Encrypt(message, aescipher.getAESKey());
            output.writeObject("AES - " + Base64.getEncoder().encodeToString(ae_msg));
            output.flush();

            // showMessage shows the message on the GUI
            // Show the unencrypted message that the Server is sending on the GUI
             */
            //these next 2 lines will need to be removed
            output.writeObject("SERVER - " + message);
            output.flush();

            showMessage("\nSERVER - " + message);
        }catch(IOException ioexception){
            chatWindow.append("\n\nSERVER ERROR: WAS NOT ABLE TO SEND MESSAGE TO CLIENT");
            ioexception.printStackTrace();
        }
    }

    private void sendConnectionCompleteMessage(String message) {
        try{
            output.writeObject("SERVER - " + message);
            output.flush();
            showMessage("\nSERVER - " + message);
        }catch(IOException ioexception){
            chatWindow.append("\n\nSERVER ERROR: WAS NOT ABLE TO SEND MESSAGE TO CLIENT");
            ioexception.printStackTrace();
        }
    }

    //updates chatWindow and displays message
    private void showMessage(final String text){
        SwingUtilities.invokeLater(
                //set aside a thread that updates the chatWindow
            new Runnable(){
                public void run(){
                    //adds messsage to the end of the docuement
                    //then updates chatWindow
                    chatWindow.append(text);
                }
            }
        );
    }

    //allow user to type into chat box if set to true
    private void ableToType(final boolean b){
        SwingUtilities.invokeLater(
            new Runnable(){
                public void run(){
                    userText.setEditable(b);
                }
            }
        );
    }
}